name: TrivialJwt NuGet Push

on:
  push:
    branches: [ main ]
    paths:
      - src/TrivialJwt
  pull_request:
    branches: [ main ]
    paths:
      - src/TrivialJwt
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release --no-restore -o src/TrivialJwt/pack src/TrivialJwt/TrivialJwt.csproj 
    - name: Push to nuget
      run: dotnet nuget push 'src/TrivialJwt/pack/*.nupkg' --api-key '${{secrets.NUGET_KEY}}' --source https://api.nuget.org/v3/index.json 
      
